glass1 = Glass.create(name: 'Martini', img_url: 'http://upload.wikimedia.org/wikipedia/commons/1/19/Coctail_glass.svg')
glass2 = Glass.create(name: 'Collins', img_url: 'http://upload.wikimedia.org/wikipedia/commons/e/e4/Collins_glass_silhouette.svg')
glass3 = Glass.create(name: 'Highball', img_url: 'http://upload.wikimedia.org/wikipedia/commons/d/db/Highball_glass_silhouette.svg')
glass4 = Glass.create(name: 'Wine', img_url: 'http://upload.wikimedia.org/wikipedia/commons/7/7e/Wineglass.svg')
glass5 = Glass.create(name: 'Yard', img_url: 'http://upload.wikimedia.org/wikipedia/commons/2/2a/Yardglass.svg')
glass6 = Glass.create(name: 'Pilsner', img_url: 'http://upload.wikimedia.org/wikipedia/commons/7/7a/Pilsner_glass_silhouette.svg')
glass7 = Glass.create(name: 'Brandy Snifter', img_url: 'http://upload.wikimedia.org/wikipedia/commons/c/cb/Brandysnifsi.svg')
glass8 = Glass.create(name: 'Champagne Flute', img_url: 'http://upload.wikimedia.org/wikipedia/commons/3/37/Flutesil.svg')
glass9 = Glass.create(name: 'Pint', img_url: 'http://upload.wikimedia.org/wikipedia/commons/9/93/Pint_glass.svg')
glass10 = Glass.create(name: 'Shot', img_url: 'http://upload.wikimedia.org/wikipedia/commons/4/40/Shot_glass.svg')
glass11 = Glass.create(name: 'Old Fashioned', img_url: 'http://upload.wikimedia.org/wikipedia/commons/9/9f/Ofgcup.svg')

ingredient1 = Ingredient.create(name: 'Rum', hex_color: 'e67e22')
ingredient2 = Ingredient.create(name: 'Cherry Tomatoes', hex_color: 'e74c3c')
ingredient3 = Ingredient.create(name: 'Mint Leaves', hex_color: '2ecc71')
ingredient4 = Ingredient.create(name: 'Coke', hex_color: '2c3e50')
ingredient5 = Ingredient.create(name: 'Vodka', hex_color: 'ecf0f1')
ingredient6 = Ingredient.create(name: 'Triple Sec', hex_color: 'f39c12')
ingredient7 = Ingredient.create(name: 'Cranberry Juice', hex_color: 'e74c3c')
ingredient8 = Ingredient.create(name: 'Lime Juice', hex_color: '2ecc71')
ingredient9 = Ingredient.create(name: 'Soda Water', hex_color: 'bdc3c7')
ingredient10 = Ingredient.create(name: 'Coffee Liqueur', hex_color: 'b48f6a')
ingredient11 = Ingredient.create(name: 'Coffee Cream', hex_color: 'f8f4f0')
ingredient12 = Ingredient.create(name: 'Gin', hex_color: 'ecf0f1')
ingredient13 = Ingredient.create(name: 'Tonic Water', hex_color: 'bdc3c7')
ingredient14 = Ingredient.create(name: 'Scotch Whisky', hex_color: 'e67e22')
ingredient15 = Ingredient.create(name: 'Sweet Vermouth', hex_color: 'e74c3c')
ingredient16 = Ingredient.create(name: 'Lemon Juice', hex_color: 'f1c40f')
ingredient17 = Ingredient.create(name: 'Sugar', hex_color: 'ecf0f1')
ingredient18 = Ingredient.create(name: 'Cherry', hex_color: 'e74c3c')
ingredient19 = Ingredient.create(name: 'Orange', hex_color: 'd35400')
ingredient20 = Ingredient.create(name: 'Gold Tequila', hex_color: 'e5c100')
ingredient21 = Ingredient.create(name: 'Sweet and Sour Mix', hex_color: 'f39c12')
ingredient22 = Ingredient.create(name: 'Cognac', hex_color: 'a3481b')
ingredient23 = Ingredient.create(name: 'Orange Liqueur', hex_color: 'd35400')
ingredient24 = Ingredient.create(name: 'Red Bull', hex_color: 'e67e22')
ingredient25 = Ingredient.create(name: 'Jagermeister', hex_color: 'f39c12')
ingredient26 = Ingredient.create(name: 'Grenadine', hex_color: 'c0292b')
ingredient27 = Ingredient.create(name: '151', hex_color: 'bdc3c7')
ingredient28 = Ingredient.create(name: 'Amaretto', hex_color: 'c0392b')
ingredient29 = Ingredient.create(name: 'Grapefruit Juice', hex_color: 'e74c3c')
ingredient30 = Ingredient.create(name: 'Pineapple Juice', hex_color: 'f1c40e')

drink1 = Drink.create(name: 'the nate mistake', glass: glass9, preparation: 'Accidentally put some tomatoes in rum...')
Component.create(drink: drink1, ingredient: ingredient1, quantity: 250)
Component.create(drink: drink1, ingredient: ingredient2, quantity: 75)

drink2 = Drink.create(name: 'mojito', glass: glass3, preparation: 'Place mint leaves in bottom of glass. Add crushed ice, Captain Morgan Original Spiced Rum, sugar, and lime juice, and muddle. Add soda water and garnish with mint leaves.')
Component.create(drink: drink2, ingredient: ingredient1, quantity: 150)
Component.create(drink: drink2, ingredient: ingredient3, quantity: 25)
Component.create(drink: drink2, ingredient: ingredient9, quantity: 200)

drink3 = Drink.create(name: 'rum and coke', glass: glass2, preparation: 'Pour over ice, garnish w/ a lime.')
Component.create(drink: drink3, ingredient: ingredient1, quantity: 50)
Component.create(drink: drink3, ingredient: ingredient4, quantity: 200)

drink4 = Drink.create(name: 'cosmo', glass: glass1, preparation: 'Pour the vodka, triple sec, cranberry juice and lime juice into a cocktail shaker half-filled with ice cubes. Shake well, strain into a cocktail glass, and serve.')
Component.create(drink: drink4, ingredient: ingredient5, quantity: 150)
Component.create(drink: drink4, ingredient: ingredient6, quantity: 75)
Component.create(drink: drink4, ingredient: ingredient7, quantity: 75)
Component.create(drink: drink4, ingredient: ingredient8, quantity: 100)

drink5 = Drink.create(name: 'white russian', glass: glass11, preparation: 'Pour vodka and coffee liqueur over ice cubes in an old-fashioned glass. Fill with light cream and serve.')
Component.create(drink: drink5, ingredient: ingredient5, quantity: 200)
Component.create(drink: drink5, ingredient: ingredient10, quantity: 100)
Component.create(drink: drink5, ingredient: ingredient11, quantity: 50)

drink6 = Drink.create(name: 'gin and tonic', glass: glass3, preparation: 'Pour the gin and tonic water into a highball glass almost filled with ice cubes. Stir will. Garnish with lime wedge')
Component.create(drink: drink6, ingredient: ingredient12, quantity: 200)
Component.create(drink: drink6, ingredient: ingredient13, quantity: 500)

drink7 = Drink.create(name: 'manhattan', glass: glass1, preparation: 'Mix and serve.')
Component.create(drink: drink7, ingredient: ingredient14, quantity: 100)
Component.create(drink: drink7, ingredient: ingredient15, quantity: 50)

drink8 = Drink.create(name: 'tom collins', glass: glass2, preparation: 'In a shaker half-filled with ice cubes, combine the gin, lemon juice, and sugar. Shake well. Strain into a Collins glass almost filled with ice cubes. Add the club soda. Stir and garnish with cherry and orange.')
Component.create(drink: drink8, ingredient: ingredient12, quantity: 200)
Component.create(drink: drink8, ingredient: ingredient16, quantity: 100)
Component.create(drink: drink8, ingredient: ingredient17, quantity: 50)
Component.create(drink: drink8, ingredient: ingredient9, quantity: 300)
Component.create(drink: drink8, ingredient: ingredient18, quantity: 50)
Component.create(drink: drink8, ingredient: ingredient19, quantity: 20)

drink9 = Drink.create(name: 'long island', glass: glass5, preparation: 'Combine alcohol in ice-filled glass and stir. Top with cola. Garnish with lemon wedge.')
Component.create(drink: drink9, ingredient: ingredient12, quantity: 100)
Component.create(drink: drink9, ingredient: ingredient5, quantity: 100)
Component.create(drink: drink9, ingredient: ingredient1, quantity: 100)
Component.create(drink: drink9, ingredient: ingredient20, quantity: 100)
Component.create(drink: drink9, ingredient: ingredient6, quantity: 100)
Component.create(drink: drink9, ingredient: ingredient21, quantity: 125)
Component.create(drink: drink9, ingredient: ingredient4, quantity: 75)

drink10 = Drink.create(name: 'sidecar', glass: glass1, preparation: 'Shake together with cracked ice and strain into martini glass. Garnish with lemon twist, and serve.')
Component.create(drink: drink10, ingredient: ingredient22, quantity: 150)
Component.create(drink: drink10, ingredient: ingredient23, quantity: 100)
Component.create(drink: drink10, ingredient: ingredient16, quantity: 50)

drink11 = Drink.create(name: 'jager bomb', glass: glass9, preparation: 'Pour red bull into glass. Add shot of jagermeister, and chug.')
Component.create(drink: drink11, ingredient: ingredient24, quantity: 400)
Component.create(drink: drink11, ingredient: ingredient25, quantity: 100)

drink12 = Drink.create(name: 'margarita', glass: glass1, preparation: 'Rim glass with lime juice and dip in salt. Shake all ingredients with ice. Strain into glass, and serve.')
Component.create(drink: drink12, ingredient: ingredient20, quantity: 150)
Component.create(drink: drink12, ingredient: ingredient6, quantity: 50)
Component.create(drink: drink12, ingredient: ingredient8, quantity: 100)

drink13 = Drink.create(name: 'hurricane', glass: glass3, preparation: 'Pour all but the juices into glass three-quarters filled with ice. Fill with equal parts of grapefruit juice and pineapple juice and serve.')
Component.create(drink: drink13, ingredient: ingredient5, quantity: 100)
Component.create(drink: drink13, ingredient: ingredient26, quantity: 25)
Component.create(drink: drink13, ingredient: ingredient12, quantity: 100)
Component.create(drink: drink13, ingredient: ingredient1, quantity: 100)
Component.create(drink: drink13, ingredient: ingredient27, quantity: 50)
Component.create(drink: drink13, ingredient: ingredient28, quantity: 100)
Component.create(drink: drink13, ingredient: ingredient6, quantity: 100)
Component.create(drink: drink13, ingredient: ingredient29, quantity: 100)
Component.create(drink: drink13, ingredient: ingredient30, quantity: 100)
